### ISSUE TITLE
Large amount of defunct processes created from 0access

### ISSUE THREAD

**Issue by dinosn** [0-complexity/0-access#10]
Hi we have the following case on all environments, 

 On the controller where zero access pod is running we have a large amount of zombie process created. 

```
root@xx1-ctrl-03:~# ps aux |  grep defunct | grep sshd | wc -l
17959
```

The process won't die and they will keep on appearing unless zero access pod get's deleted and started again. 

To find from where the zombie processes are coming you can execute the following

```
parents_of_zombies=$(ps -ef | grep [d]efunct | awk '{print $3}' | sort | uniq | egrep -v '^1$'); echo "$parents_of_zombies"
```

After the pod is deleted and respawn again the issue is cleared. 

```
root@xx1-ctrl-03:~# ps aux |  grep defunct | grep sshd | wc -l
0
root@xx1-ctrl-03:~#
```

**Comment by ashraffouda** [comment]
https://github.com/0-complexity/0-access/commit/e6b3b3e8e0676340e33ba515843c1e0fc54f0985
